import { Artist } from '../types/artist.types';
import { Project } from '../types/project.types';

export const mockArtists: Artist[] = [
  {
    id: '1',
    name: 'Nicholas Wu',
    avatar: '/images/nicholas_avatar.jpg',
    banner: '/images/banner_main.jpg',
    school: 'LMU',
    major: 'Film & TV Production',
    graduationYear: '2024',
    about:
      'Nicholas Wu is a storyboard artist and animator in Los Angeles, California. Nicholas studied Film & TV Production and Screenwriting at Loyola Marymount University and has worked on both live-action and animation projects.',
    topSkills: ['Storyboard Pro', 'Blender', 'Photoshop'],
    boardTypes: ['Action Board', 'Cinematic'],
    portfolio: [
      {
        id: 'p1',
        title: 'Way of the Shadow',
        image: '/images/project1.jpg',
        tags: ['Action Boards', 'Commercial', 'Martial Arts'],
        category: 'action',
      },
      {
        id: 'p2',
        title: 'Faces in the Water',
        image: '/images/project2.jpg',
        tags: ['Cinematic Boards', 'Short Film', 'Drama'],
        category: 'cinematic',
      },
    ],
    availability: {
      status: 'open',
      nextAvailable: 'Oct 2025',
      rate: 450,
    },
    uploadDate: '2025-06-15T10:00:00Z',
    viewCount: 1240,
  },
  {
    id: '2',
    name: 'Maya Patel',
    avatar: '/images/nicholas_avatar.jpg',
    banner: '/images/banner_main.jpg',
    school: 'CalArts',
    major: 'Character Animation',
    graduationYear: '2023',
    about:
      'Maya Patel is a storyboard artist and character designer based in Burbank, CA. She graduated from CalArts with a focus on character animation and has contributed boards to several animated series and indie shorts.',
    topSkills: ['Storyboard Pro', 'Procreate', 'After Effects'],
    boardTypes: ['Comedy Board', 'Character-Driven'],
    portfolio: [
      {
        id: 'p3',
        title: 'Lunar Rabbit',
        image: '/images/project1.jpg',
        tags: ['Comedy Boards', 'Animated Series', 'Fantasy'],
        category: 'comedy',
      },
      {
        id: 'p4',
        title: 'Late Shift',
        image: '/images/project2.jpg',
        tags: ['Character-Driven', 'Slice of Life', 'Indie'],
        category: 'character',
      },
    ],
    availability: {
      status: 'busy',
      nextAvailable: 'Mar 2026',
      rate: 500,
    },
    isPremium: true,
    uploadDate: '2025-08-22T14:30:00Z',
    viewCount: 3450,
  },
  {
    id: '3',
    name: 'Jordan Lee',
    avatar: '/images/nicholas_avatar.jpg',
    banner: '/images/banner_main.jpg',
    school: 'SVA',
    major: 'Visual Narrative',
    graduationYear: '2025',
    about:
      'Jordan Lee is a storyboard and concept artist from New York. He specializes in sci-fi and horror visual storytelling, blending cinematic compositions with graphic novel aesthetics.',
    topSkills: ['Clip Studio Paint', 'Photoshop', 'Blender'],
    boardTypes: ['Cinematic', 'Horror'],
    portfolio: [
      {
        id: 'p5',
        title: 'Station Nine',
        image: '/images/project1.jpg',
        tags: ['Cinematic Boards', 'Sci-Fi', 'Feature'],
        category: 'cinematic',
      },
      {
        id: 'p6',
        title: 'The Hollow',
        image: '/images/project2.jpg',
        tags: ['Horror', 'Short Film', 'Atmospheric'],
        category: 'horror',
      },
    ],
    availability: {
      status: 'open',
      nextAvailable: 'Feb 2026',
      rate: 350,
    },
    uploadDate: '2025-11-03T09:15:00Z',
    viewCount: 870,
  },
  {
    id: '4',
    name: 'Anika Torres',
    avatar: '/images/nicholas_avatar.jpg',
    banner: '/images/banner_main.jpg',
    school: 'RISD',
    major: 'Illustration',
    graduationYear: '2024',
    about:
      'Anika Torres is an illustrator and storyboard artist from Providence, RI. Her work focuses on emotionally rich, dialogue-heavy sequences for animation and live-action drama.',
    topSkills: ['Storyboard Pro', 'Photoshop', 'Procreate'],
    boardTypes: ['Dialogue Board', 'Drama'],
    portfolio: [
      {
        id: 'p7',
        title: 'Between the Lines',
        image: '/images/project1.jpg',
        tags: ['Dialogue Boards', 'Drama', 'Indie Film'],
        category: 'dialogue',
      },
      {
        id: 'p8',
        title: 'Homecoming',
        image: '/images/project2.jpg',
        tags: ['Drama', 'Student Film', 'Emotional'],
        category: 'drama',
      },
    ],
    availability: {
      status: 'open',
      rate: 400,
    },
    uploadDate: '2025-12-10T16:45:00Z',
    viewCount: 2100,
  },
  {
    id: '5',
    name: 'Derek Okafor',
    avatar: '/images/nicholas_avatar.jpg',
    banner: '/images/banner_main.jpg',
    school: 'USC',
    major: 'Animation & Digital Arts',
    graduationYear: '2023',
    about:
      'Derek Okafor is a Los Angeles-based storyboard artist with experience in commercial and music video production. Known for dynamic action sequences and bold compositions.',
    topSkills: ['Storyboard Pro', 'After Effects', 'Premiere Pro'],
    boardTypes: ['Action Board', 'Commercial'],
    portfolio: [
      {
        id: 'p9',
        title: 'Overdrive',
        image: '/images/project1.jpg',
        tags: ['Action Boards', 'Music Video', 'High Energy'],
        category: 'action',
      },
      {
        id: 'p10',
        title: 'Neon District',
        image: '/images/project2.jpg',
        tags: ['Commercial', 'Urban', 'Stylized'],
        category: 'commercial',
      },
    ],
    availability: {
      status: 'unavailable',
    },
    isPremium: true,
    uploadDate: '2026-01-18T11:00:00Z',
    viewCount: 5670,
  },
];

export const mockProjects: Project[] = [
  {
    id: '1',
    title: 'Soulstealers',
    subtitle: 'LMU Undergrad 3rd-Year Thesis',
    image: '/images/Soulstealers.jpg',
    logline:
      'At the height of the 1768 Sorcery Scare in Qing Dynasty China, a bridge builder from out of town races to find the real cause of the local kid\'s possession before the xenophobic town deems him guilty.',
    school: 'LMU',
    format: 'Short Film',
    length: '15 min',
    timeline: '1 Month',
    productionType: 'Student',
    shotlistReady: true,
    locationSecured: true,
    isPaid: true,
    visualDeckUrl: '#',
    contactInfo: {
      twitter: '#',
      instagram: '#',
      email: 'contact@example.com',
    },
    uploadDate: '2025-07-10T08:00:00Z',
    viewCount: 2340,
  },
  {
    id: '2',
    title: 'Parallax',
    subtitle: 'CalArts Senior Thesis Film',
    image: '/images/Soulstealers.jpg',
    logline:
      'A retired astronaut suffering from memory loss discovers that the strange visions she keeps having aren\'t hallucinations \u2014 they\'re transmissions from a version of herself that never came home.',
    school: 'CalArts',
    format: 'Short Film',
    length: '12 min',
    timeline: '2 Months',
    productionType: 'Student',
    shotlistReady: true,
    locationSecured: false,
    isPaid: false,
    contactInfo: {
      instagram: '#',
      email: 'parallax@example.com',
    },
    uploadDate: '2025-09-05T12:00:00Z',
    viewCount: 1870,
  },
  {
    id: '3',
    title: 'Glass Garden',
    subtitle: 'Indie Animated Short',
    image: '/images/Soulstealers.jpg',
    logline:
      'In a city where emotions manifest as plants, a florist who feels nothing must tend to the overgrown grief of a stranger before it consumes the entire neighborhood.',
    school: 'SVA',
    format: 'Short Film',
    length: '8 min',
    timeline: '3 Months',
    productionType: 'Indie',
    shotlistReady: false,
    locationSecured: true,
    isPaid: true,
    visualDeckUrl: '#',
    contactInfo: {
      twitter: '#',
      email: 'glassgarden@example.com',
    },
    uploadDate: '2025-10-20T15:30:00Z',
    viewCount: 950,
  },
  {
    id: '4',
    title: 'VANTA',
    subtitle: 'Nike x Foot Locker Campaign',
    image: '/images/Soulstealers.jpg',
    logline:
      'A 60-second spot following a dancer through impossible architecture as each move transforms the world around her into bold, kinetic geometry.',
    school: 'USC',
    format: 'Commercial',
    length: '60 sec',
    timeline: '2 Weeks',
    productionType: 'Commercial',
    shotlistReady: true,
    locationSecured: true,
    isPaid: true,
    visualDeckUrl: '#',
    contactInfo: {
      twitter: '#',
      instagram: '#',
      email: 'vanta@example.com',
    },
    uploadDate: '2025-12-01T09:00:00Z',
    viewCount: 4200,
  },
  {
    id: '5',
    title: 'Undertow',
    subtitle: 'RISD MFA Thesis',
    image: '/images/Soulstealers.jpg',
    logline:
      'Two estranged siblings return to their childhood beach house to settle their late mother\'s estate, only to find that the house won\'t let them leave until they confront what tore them apart.',
    school: 'RISD',
    format: 'Short Film',
    length: '20 min',
    timeline: '6 Weeks',
    productionType: 'Student',
    shotlistReady: true,
    locationSecured: true,
    isPaid: false,
    contactInfo: {
      email: 'undertow@example.com',
    },
    uploadDate: '2026-01-08T14:00:00Z',
    viewCount: 680,
  },
  {
    id: '6',
    title: 'Midnight Frequency',
    subtitle: 'Independent Music Video',
    image: '/images/Soulstealers.jpg',
    logline:
      'A pirate radio DJ in 1990s Lagos broadcasts forbidden songs that literally bring the city\'s murals to life, drawing the attention of a government determined to silence him.',
    school: 'LMU',
    format: 'MV',
    length: '4 min',
    timeline: '3 Weeks',
    productionType: 'Indie',
    shotlistReady: false,
    locationSecured: false,
    isPaid: true,
    visualDeckUrl: '#',
    contactInfo: {
      twitter: '#',
      instagram: '#',
      email: 'midfreq@example.com',
    },
    uploadDate: '2026-02-01T10:00:00Z',
    viewCount: 3100,
  },
];
